site_name: p4a.net
extra:
  homepage: https://p4a.net
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/seajoshc
    - icon: fontawesome/brands/linkedin 
      link: https://linkedin.com/in/seajoshc
plugins:
  - search
theme:
  name: material
  font:
    text: Red Hat Mono
  favicon: images/user-astronaut-solid.svg
  icon:
    logo: fontawesome/solid/user-astronaut
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - toc.integrate